name: 一键打包带环境
on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装Java17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: 打包项目
        run: mvn clean package -DskipTests

      - name: 打包绿色运行包
        run: |
          mkdir 运行包
          copy target\*.jar 运行包\
          echo @echo off > 运行包\启动.bat
          echo java -jar *.jar >> 运行包\启动.bat
          echo pause >> 运行包\启动.bat

      - name: 上传成品
        uses: actions/upload-artifact@v4
        with:
          name: 小蚕一键运行包
          path: 运行包
